# Generated by Django 5.0.3 on 2024-03-14 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='services',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
