# Generated by Django 5.0.3 on 2024-03-15 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0003_rename_image_photo_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='clients',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
