# Generated by Django 5.0.3 on 2024-05-06 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0006_photoprojects_photoservices_projects_delete_photo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='photos',
        ),
        migrations.DeleteModel(
            name='PhotoProduct',
        ),
        migrations.DeleteModel(
            name='Products',
        ),
    ]
