# Generated by Django 5.0.3 on 2024-05-10 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0007_remove_products_photos_delete_photoproduct_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Developers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='')),
                ('kasb', models.CharField(max_length=100)),
                ('instagram', models.CharField(max_length=50)),
                ('github', models.CharField(max_length=50)),
                ('linkedin', models.CharField(max_length=50)),
                ('telegram', models.CharField(max_length=50)),
                ('facebook', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('ayol', 'Ayol'), ('erkak', 'Erkak')], max_length=5)),
            ],
        ),
    ]
