# Generated by Django 5.0.3 on 2024-05-10 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0008_developers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developers',
            name='facebook',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='developers',
            name='github',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='developers',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='developers',
            name='instagram',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='developers',
            name='linkedin',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
