# Generated by Django 5.0.3 on 2024-05-10 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0009_alter_developers_facebook_alter_developers_github_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='developers',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='developers',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
