# Generated by Django 5.0.3 on 2024-05-10 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0010_developers_created_at_developers_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
