# Generated by Django 5.0.3 on 2024-05-10 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0011_projects_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='services',
            field=models.TextField(blank=True, null=True),
        ),
    ]
